Rush 01/chat/urls.py
from django.urls import path
# from . import consumers
from . import views

urlpatterns = [
    path('chat/', views.DiscussionListView.as_view(), name='discussions'),
    path('chat/<int:pk>/', views.DiscussionDetailView.as_view(), name='conv'),
]

# wspatterns = [
#     path('ws/chat/<int:pk>/', consumers.ChatConsumer.as_asgi()),
# ]

Rush 01/forum/urls.py
from django.urls import path

from . import views


urlpatterns = [
    # path('forum/', RegisterFormView.as_view(), name='register'),
	path('forum/', views.Forum.as_view(), name='forum'),
	path('forum/<int:pk>/', views.ForumDetail.as_view(), name='forum detail'),
	path('publish/', views.Publish.as_view(), name='publish')
]

Rush 01/rush01/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('chat.urls')),
    path('', include('forum.urls')),
    path('', include('member.urls')),
]

# SERVER MEDIA

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Rush 01/forum/models.py
from django.db import models
from django.contrib.auth.models import User
from member.models import MemberModel

# Create your models here.

class ForumModel(models.Model):
	author = models.ForeignKey(User, on_delete=models.CASCADE, blank=False)
	userinfo = models.ForeignKey(MemberModel, on_delete=models.CASCADE, blank=False)
	title = models.CharField(blank=False, max_length=64)
	content = models.TextField(blank=False)
	created = models.DateTimeField(blank=False, auto_now_add=True)
	id = models.IntegerField(primary_key=True)

class CommentModel(models.Model):
	author = models.ForeignKey(User, on_delete=models.CASCADE, blank=False)
	userinfo = models.ForeignKey(MemberModel, on_delete=models.CASCADE, blank=False)
	content = models.TextField(blank=False)
	created = models.DateTimeField(blank=False, auto_now_add=True)
	deep = models.ForeignKey('self', blank=True, null=True, on_delete=models.CASCADE)
	shallow = models.ForeignKey(ForumModel, blank=True, null=True, on_delete=models.CASCADE)
	id = models.IntegerField(primary_key=True)

Rush 01/forum/forms.py
from django import forms
from django.forms import ModelForm
from .models import ForumModel, CommentModel

class CreateForumForm(ModelForm):
	class Meta:
		model = ForumModel
		fields = ['title', 'content']

class CreateCommentForm(ModelForm):
	class Meta:
		model = CommentModel
		fields = ['content']

Rush 01/forum/views.py
from django.shortcuts import render, redirect, reverse
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, FormView
from django.core.paginator import Paginator
from django.contrib.auth.models import User
from .models import CommentModel, ForumModel
from .forms import CreateForumForm, CreateCommentForm
from member.models import MemberModel

# Create your views here.

class Forum(ListView):
	model = ForumModel
	template_name = "forum/forums.html"

	def get_context_data(self, **kwargs):
		context = super(Forum, self).get_context_data(**kwargs)
		context['object_list'] = Paginator(ForumModel.objects.order_by('-created'), 10).page(self.request.GET.get('page', 1))
		if self.request.user.is_authenticated:
			if MemberModel.objects.filter(user=self.request.user).exists():
				context['userinfo'] = MemberModel.objects.get(user=self.request.user)
			context['user'] = self.request.user
		return context

class ForumDetail(FormView):
	form_class = CreateCommentForm
	template_name = "forum/foruminfo.html"
	success_url = reverse_lazy('forum')

	def get_success_url(self) -> str:
		return super().get_success_url() + str(self.kwargs['pk'])

	def get(self, request, *args, **kwargs):
		if not ForumModel.objects.filter(id=int(self.kwargs['pk'])):
			return redirect(reverse('forum'))
		if self.request.user.is_authenticated:
			if not MemberModel.objects.filter(user=self.request.user).exists():
				MemberModel.objects.create(user=self.request.user)
		return super().get(request, *args, **kwargs)

	def get_context_data(self, **kwargs):
		context =  super().get_context_data(**kwargs)
		context['forum'] = ForumModel.objects.get(id=int(self.kwargs['pk']))
		context['isuser'] = self.request.user.is_authenticated
		if self.request.user.is_authenticated:
			if MemberModel.objects.filter(user=self.request.user).exists():
				context['userinfo'] = MemberModel.objects.get(user=self.request.user)
		return context
	
	def form_valid(self, form):
		if not self.request.user.is_authenticated:
			return super().form_invalid(form)
		if 'content' not in form.cleaned_data:
			return super().form_invalid(form)
		if 'parrentForm' in self.request.POST and 'parrentComment' in self.request.POST:
			return super().form_invalid(form)
		if 'parrentForm' in self.request.POST and ForumModel.objects.filter(id=int(self.request.POST['parrentForm'])).exists():
			if not User.objects.filter(username=self.request.user).exists():
				return super().form_invalid(form)
			CommentModel.objects.create(
				author = User.objects.get(username=self.request.user), 
				content = form.cleaned_data['content'],
				userinfo = MemberModel.objects.get(user=self.request.user),
				shallow = ForumModel.objects.get(id=int(self.request.POST['parrentForm']))
			)
		elif 'parrentComment' in self.request.POST and CommentModel.objects.filter(id=int(self.request.POST['parrentComment'])).exists():
			if not User.objects.filter(username=self.request.user).exists():
				return super().form_invalid(form)
			CommentModel.objects.create(
				author = User.objects.get(username=self.request.user), 
				content = form.cleaned_data['content'],
				userinfo = MemberModel.objects.get(user=self.request.user),
				deep = CommentModel.objects.get(id=int(self.request.POST['parrentComment']))
			)
		return super().form_valid(form)

class Publish(CreateView):
	model = ForumModel
	form_class = CreateForumForm
	template_name = "forum/publish.html"
	success_url = reverse_lazy('forum')

	def get(self, request, *args, **kwargs):
		if not request.user.is_authenticated:
			return redirect(reverse('home'))
		if self.request.user.is_authenticated:
			if not MemberModel.objects.filter(user=self.request.user).exists():
				MemberModel.objects.create(user=self.request.user)
		return super().get(request, *args, **kwargs)

	def form_valid(self, form):
		user = self.request.user
		userinfo = MemberModel.objects.get(user=self.request.user)
		form.instance.author = user
		form.instance.userinfo = userinfo
		return super(Publish, self).form_valid(form)

	def get_context_data(self, **kwargs):
		context = super(Publish, self).get_context_data(**kwargs)
		context['isuser'] = self.request.user.is_authenticated
		if self.request.user.is_authenticated:
			context['username'] = self.request.user
		return context

Rush 01/forum/templates/forum/foruminfo.html
{% extends 'base.html' %}

{% load bootstrap3 %}

{% block title %}{{ forum.title }} By: {{ forum.author }}{% endblock %}

{% block content %}
<div class="topic">
	<table>
		<tr>
			<th>
				{{ forum.title }}
				{% if forum.userinfo.avatar %}
					By: <img src="{{ forum.userinfo.avatar.url }}" style="max-width:30px;" > <a href="{% url 'user' pk=forum.author.id %}">{{ forum.author }}</a>
				{% else %}
					By: <img src="/media/default.png" style="max-width:30px;" > <a href="{% url 'user' pk=forum.author.id %}">{{ forum.author }}</a>
				{% endif %}
			</th>
		</tr>
		<tr>
			<td>
				{{ forum.content|linebreaksbr }}
			</td>
		</tr>
		<tr>
			<td>
				{{ forum.created }}
			</td>
		</tr>
	</table>
    {% if isuser %}
        <form action="" method="post" class="form-comment">
            {% csrf_token %}
            {# {% bootstrap_form form show_label=False %} #}
            {% bootstrap_field form.content show_label=False %}
            <input id="parrentForm" name="parrentForm" type="hidden" value="{{ forum.id }}">
            <input style="position: relative; right:0" type="submit" class="btn btn-primary" value="Comment" />
        </form>
    {% endif %}
	<ul>
        {% for comment in forum.commentmodel_set.all %}
            {% include 'forum/tools/comment_recursion.html' %}
        {% endfor %}
	<ul>
</div>
{% endblock content %}

Rush 01/forum/templates/forum/forums.html
{% extends 'base.html' %}

{% load bootstrap3 %}

{% block title %}Forums{% endblock %}

{% block h1 %}Forums - List of topics{% endblock %}

{% block content %}
	<table style="width: 100%;">
		{% for members in object_list %}
			<tr>
				<th style="width: 75%; text-align: left">
					<a href="/forum/{{ members.id }}">{{ members.title }}</a>
					{% if members.userinfo.avatar %}
						By: <img src="{{  members.userinfo.avatar.url }}" style="max-width:30px;" > <a href="{% url 'user' pk=members.author.id %}">{{ members.author }}</a>
					{% else %}
						By: <img src="/media/default.png" style="max-width:30px;" > <a href="{% url 'user' pk=members.author.id %}">{{ members.author }}</a>
					{% endif %}
				</th>
				<td style="width:1%"></td>
				<th>
					{{ members.created }}
				</th>
				<th>
					{{ members.created|timesince }} ago
				</th>
			</tr>
			<tr>
				<td style="width: 75%; text-align: left">
					{{ members.content|truncatechars:300 }}
				</td>
			</tr>
			<tr>
				<td>
					<br>
				</td>
			</tr>
			{% if members.commentmodel_set.all.count > 0 %}
				<tr>
					<th style="text-align: left">
						Comments
					</th>
				</tr>
			{% else %}
				<tr>
					<th style="text-align: left">
						This post has no comments
					</th>
				</tr>
			{% endif %}
			{% for comment in members.commentmodel_set.all|slice:":4" %}
				<tr>
					<th style="width: 75%; text-align: left">
						{% if comment.userinfo.avatar %}
							<p class="author"><img src="{{ comment.userinfo.avatar.url }}" style="max-width:30px;" > <a href="{% url 'user' pk=comment.author.id %}">{{ comment.author }}</a></p>
						{% else %}
							<p class="author"><img src="/media/default.png" style="max-width:30px;" > <a href="{% url 'user' pk=comment.author.id %}">{{ comment.author }}</a></p>
						{% endif %}
					</th>
					<td style="width:1%"></td>
					<th>
						{{ members.created }}
					</th>
					<th>
						{{ members.created|timesince }} ago
					</th>
				</tr>
				<tr>
					<td style="width: 75%; text-align: left">
						{{ comment.content }}
					</td>
				</tr>
			{% endfor %}
			<tr>
				<td>
					<br />
					<br />
				</td>
			</tr>
		{% endfor %}
	</table>
	{% bootstrap_pagination object_list %}
    <p><a href="{% url 'publish' %}">Post a new topic</a></p>
{% endblock content %}

Rush 01/forum/templates/forum/publish.html
{% extends "base.html" %}

{% load bootstrap3 %}

{% block title %}Post{% endblock %}

{% block content %}
    <form action="{% url 'publish' %}" method="post" class="form-login">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
        <button type="submit" class="btn btn-primary">Post</button>
        {% endbuttons %}
    </form>
{% endblock %}